"""Molecular Circuit Candidate ORM models.

These tables are independent of the existing circuit extraction pipeline.
They store candidate circuits generated by the Molecular-granularity circuit
extraction v2 system — graph engine output, DeepSeek judgments, and quality
gate results. Candidates reside in a dedicated pool and do NOT flow into
mirror_region_circuits, final_*, or kg_* automatically.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Any

from sqlalchemy import DateTime, ForeignKey, Integer, String, func
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base


class MolecularCircuitCandidateRun(Base):
    """One molecular circuit extraction run — tracks lifecycle and summary stats.

    The run progresses through: pending → running → completed/failed/cancelled.
    Packs are processed sequentially with checkpoint support for pause/resume.
    """

    __tablename__ = "molecular_circuit_candidate_runs"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    status: Mapped[str] = mapped_column(
        String(32), nullable=False, default="pending"
    )
    provider: Mapped[str | None] = mapped_column(String(32), nullable=True)
    model_name: Mapped[str | None] = mapped_column(String(128), nullable=True)
    candidate_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    pack_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    total_raw_topologies: Mapped[int | None] = mapped_column(
        Integer, nullable=True
    )
    total_passed: Mapped[int | None] = mapped_column(Integer, nullable=True)
    total_failed: Mapped[int | None] = mapped_column(Integer, nullable=True)
    high_confidence: Mapped[int] = mapped_column(
        Integer, nullable=False, default=0
    )
    medium_confidence: Mapped[int] = mapped_column(
        Integer, nullable=False, default=0
    )
    low_confidence: Mapped[int] = mapped_column(
        Integer, nullable=False, default=0
    )
    progress_json: Mapped[dict[str, Any]] = mapped_column(
        JSONB, nullable=False, default=dict
    )
    result_summary_json: Mapped[dict[str, Any]] = mapped_column(
        JSONB, nullable=False, default=dict
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )


class MirrorMolecularCircuitCandidate(Base):
    """One candidate circuit in the molecular circuit candidate pool.

    Each candidate is the result of:
      1. Graph engine motif generation + canonical dedup + topology pre-score
      2. Module classifier multi-label assignment + packing
      3. DeepSeek semantic judgment (topology, anatomy, function, evidence)
      4. Quality gate validation (deterministic checks + dedup merge)

    Uniqueness is enforced by (canonical_key, extraction_run_id) for idempotent
    writes — retries and duplicate submissions do NOT produce duplicate records.
    """

    __tablename__ = "mirror_molecular_circuit_candidates"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    extraction_run_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("molecular_circuit_candidate_runs.id"),
        nullable=True,
    )
    pack_id: Mapped[int] = mapped_column(Integer, nullable=False)
    canonical_key: Mapped[str] = mapped_column(
        String(512), nullable=False
    )

    # Topology info
    topology_type: Mapped[str | None] = mapped_column(
        String(64), nullable=True
    )
    anatomical_pattern: Mapped[str | None] = mapped_column(
        String(64), nullable=True
    )
    closed_loop: Mapped[bool | None] = mapped_column(nullable=True, default=False)
    node_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    edge_count: Mapped[int | None] = mapped_column(Integer, nullable=True)

    # DeepSeek review
    name_en: Mapped[str | None] = mapped_column(String(512), nullable=True)
    name_cn: Mapped[str | None] = mapped_column(String(512), nullable=True)
    functional_module: Mapped[list[Any]] = mapped_column(
        JSONB, nullable=False, default=list
    )
    known_status: Mapped[str | None] = mapped_column(String(64), nullable=True)

    # Confidence
    overall_confidence: Mapped[float | None] = mapped_column(nullable=True)
    confidence_level: Mapped[str | None] = mapped_column(
        String(16), nullable=True
    )

    # Scores
    topology_score: Mapped[float | None] = mapped_column(nullable=True)
    anatomical_score: Mapped[float | None] = mapped_column(nullable=True)
    functional_score: Mapped[float | None] = mapped_column(nullable=True)
    evidence_score: Mapped[float | None] = mapped_column(nullable=True)
    pre_score: Mapped[float | None] = mapped_column(nullable=True)

    # Detailed data
    nodes_json: Mapped[list[Any]] = mapped_column(
        JSONB, nullable=False, default=list
    )
    edges_json: Mapped[list[Any]] = mapped_column(
        JSONB, nullable=False, default=list
    )
    llm_raw_response_json: Mapped[dict[str, Any]] = mapped_column(
        JSONB, nullable=False, default=dict
    )
    validation_result_json: Mapped[dict[str, Any]] = mapped_column(
        JSONB, nullable=False, default=dict
    )

    # Status tracking
    review_status: Mapped[str] = mapped_column(
        String(32), nullable=False, default="candidate"
    )
    parent_circuit_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), nullable=True
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )
