from __future__ import annotations


ORG_HUMAN_ID = "ORG_HUMAN"
SYS_NERVOUS_ID = "SYS_NERVOUS"
ORGN_HUMAN_BRAIN_ID = "ORGN_HUMAN_BRAIN"
DIV_NON_LOBE_DIVISION_BRAIN_ID = "DIV_NON_LOBE_DIVISION_BRAIN"

