-- Migration: Molecular Circuit Candidate Pool (v2)
-- Date: 2026-07-21
-- Purpose: Create tables for Molecular-granularity circuit extraction v2:
--   1. molecular_circuit_candidate_runs — extraction run tracking
--   2. mirror_molecular_circuit_candidates — candidate circuit pool (Mirror KG layer)
-- These tables are independent of existing circuit extraction tables and do NOT
-- write to mirror_region_circuits, final_*, or kg_*.

BEGIN;

-- ============================================================================
-- Table 1: Molecular Circuit Candidate Runs
-- Tracks each extraction run through its lifecycle (pending → running → completed/failed)
-- ============================================================================
CREATE TABLE IF NOT EXISTS molecular_circuit_candidate_runs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    status VARCHAR(32) NOT NULL DEFAULT 'pending',
    provider VARCHAR(32),
    model_name VARCHAR(128),
    candidate_count INT,
    pack_count INT,
    total_raw_topologies INT,
    total_passed INT,
    total_failed INT,
    high_confidence INT DEFAULT 0,
    medium_confidence INT DEFAULT 0,
    low_confidence INT DEFAULT 0,
    progress_json JSONB DEFAULT '{}',
    result_summary_json JSONB DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================================
-- Table 2: Mirror Molecular Circuit Candidates
-- Stores all candidate circuits generated by the v2 pipeline (graph engine +
-- module classifier + DeepSeek + quality gate). Each candidate is uniquely
-- identified by (canonical_key, extraction_run_id).
-- ============================================================================
CREATE TABLE IF NOT EXISTS mirror_molecular_circuit_candidates (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    extraction_run_id UUID REFERENCES molecular_circuit_candidate_runs(id),
    pack_id INT NOT NULL,
    canonical_key VARCHAR(512) NOT NULL,

    -- Topology info
    topology_type VARCHAR(64),
    anatomical_pattern VARCHAR(64),
    closed_loop BOOLEAN DEFAULT false,
    node_count INT,
    edge_count INT,

    -- DeepSeek review
    name_en VARCHAR(512),
    name_cn VARCHAR(512),
    functional_module JSONB DEFAULT '[]',
    known_status VARCHAR(64),

    -- Confidence
    overall_confidence FLOAT,
    confidence_level VARCHAR(16),

    -- Scores
    topology_score FLOAT,
    anatomical_score FLOAT,
    functional_score FLOAT,
    evidence_score FLOAT,
    pre_score FLOAT,

    -- Detailed data
    nodes_json JSONB NOT NULL,
    edges_json JSONB NOT NULL,
    llm_raw_response_json JSONB DEFAULT '{}',
    validation_result_json JSONB DEFAULT '{}',

    -- Status tracking
    review_status VARCHAR(32) NOT NULL DEFAULT 'candidate',
    parent_circuit_id UUID,

    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    UNIQUE (canonical_key, extraction_run_id)
);

-- Indexes for common query patterns
CREATE INDEX IF NOT EXISTS idx_mcc_extraction_run_id
    ON mirror_molecular_circuit_candidates(extraction_run_id);
CREATE INDEX IF NOT EXISTS idx_mcc_canonical_key
    ON mirror_molecular_circuit_candidates(canonical_key);
CREATE INDEX IF NOT EXISTS idx_mcc_confidence_level
    ON mirror_molecular_circuit_candidates(confidence_level);
CREATE INDEX IF NOT EXISTS idx_mcc_topology_type
    ON mirror_molecular_circuit_candidates(topology_type);
CREATE INDEX IF NOT EXISTS idx_mcc_review_status
    ON mirror_molecular_circuit_candidates(review_status);

COMMIT;
