"""Molecular Circuit Graph Engine — Phase 1 of Molecular Circuit Extraction v2.

Builds a directed adjacency graph from Mirror KG molecular connections and
generates candidate topologies using deterministic graph algorithms.

9 motif types, real-time canonical-key dedup, topology pre-scoring.
Output: raw_topology_candidates.jsonl (does NOT write to DB directly).
"""

from __future__ import annotations

import json
import logging
import tempfile
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.candidate import CandidateBrainRegion
from app.models.mirror_kg import MirrorRegionConnection

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class GraphEngineConfig:
    """Configurable caps and limits for graph building and motif generation."""

    # Motif generation caps
    max_directed_cycles_3: int = 10000
    max_feedforward_loops_3: int = 10000
    max_reciprocal_pairs_3: int = 5000
    max_convergent_motifs: int = 5000
    max_divergent_motifs: int = 5000
    max_relay_pathways: int = 20000
    max_closed_loops_4_8: int = 5000
    max_cortico_subcortical_loops: int = 5000
    max_cross_module_loops: int = 5000

    # Path limits
    max_relay_depth: int = 6
    max_paths_per_start: int = 10
    max_loops_bounded_dfs: int = 1000  # per SCC when >50 nodes
    max_per_hub_convergent: int = 20
    max_per_hub_divergent: int = 20
    hub_count: int = 50

    # Filtering
    pre_score_cutoff: float = 0.1

    # Performance
    scc_small_threshold: int = 50

    # Graph build filters
    granularity_level: str = "molecular_attr"
    min_confidence: float | None = None
    exclude_rejected: bool = True


# ---------------------------------------------------------------------------
# Data structures
# ---------------------------------------------------------------------------


@dataclass
class NodeInfo:
    """Lightweight node representation for graph algorithms."""
    region_id: str
    name_en: str = ""
    name_cn: str = ""
    functional_domains: list[str] = field(default_factory=list)


@dataclass
class EdgeRecord:
    """Lightweight edge record for graph algorithms."""
    edge_id: str
    source_id: str
    target_id: str
    connection_type: str = ""
    directionality: str = "directed"
    confidence: float = 0.0
    evidence_count: int = 0
    strength: str | None = None
    modality: str | None = None


@dataclass
class TopologyCandidate:
    """A single candidate topology generated by the graph engine."""

    topology_type: str
    anatomical_pattern: str
    is_closed: bool
    node_ids: list[str]
    edge_ids: list[str]
    canonical_key: str
    pre_score: float = 0.0
    avg_confidence: float = 0.0
    total_evidence: int = 0
    node_count: int = 0
    edge_count: int = 0
    extra: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return {
            "topology_type": self.topology_type,
            "anatomical_pattern": self.anatomical_pattern,
            "is_closed": self.is_closed,
            "node_ids": self.node_ids,
            "edge_ids": self.edge_ids,
            "canonical_key": self.canonical_key,
            "pre_score": self.pre_score,
            "avg_confidence": self.avg_confidence,
            "total_evidence": self.total_evidence,
            "node_count": self.node_count,
            "edge_count": self.edge_count,
            **self.extra,
        }


@dataclass
class GraphEngineResult:
    """Result from build_graph_and_generate_candidates."""
    nodes: dict[str, NodeInfo]
    edges: dict[str, EdgeRecord]
    adjacency: dict[str, set[str]]
    candidates: list[TopologyCandidate] = field(default_factory=list)
    stats: dict[str, Any] = field(default_factory=dict)


# ---------------------------------------------------------------------------
# Canonical key functions
# ---------------------------------------------------------------------------

MOTIF_CLOSED_TYPES = frozenset({
    "directed_cycle_3",
    "closed_loop_4_8",
    "cortico_subcortical_loop",
    "cross_module_loop",
})


def canonical_key_directed_cycle(node_ids: list[str]) -> str:
    """Rotate to lexicographically minimal start for directed cycles."""
    if not node_ids:
        return ""
    rotations = [node_ids[i:] + node_ids[:i] for i in range(len(node_ids))]
    return "::".join(min(rotations))


def canonical_key_pathway(node_ids: list[str]) -> str:
    """Keep direction, normalize so start < end lexicographically."""
    if not node_ids:
        return ""
    if node_ids[0] < node_ids[-1]:
        return "::".join(node_ids)
    return "::".join(reversed(node_ids))


def canonical_key_convergent(sources: list[str], target: str) -> str:
    """Sort sources alphabetically, then target."""
    sorted_sources = sorted(sources)
    return f"convergent::{':'.join(sorted_sources)}->{target}"


def canonical_key_divergent(source: str, targets: list[str]) -> str:
    """Source first, then sorted targets."""
    sorted_targets = sorted(targets)
    return f"divergent::{source}->{':'.join(sorted_targets)}"


def canonical_key_reciprocal(node_ids: list[str]) -> str:
    """Reciprocal pair chain: rotate to lexicographically minimal start."""
    if not node_ids:
        return ""
    rotations = [node_ids[i:] + node_ids[:i] for i in range(len(node_ids))]
    return "reciprocal::" + "::".join(min(rotations))


def make_canonical_key(node_ids: list[str], topology_type: str) -> str:
    """Dispatch to the correct canonical key function based on type."""
    if topology_type in MOTIF_CLOSED_TYPES:
        return canonical_key_directed_cycle(node_ids)
    elif topology_type == "reciprocal_pair_3":
        return canonical_key_reciprocal(node_ids)
    elif topology_type in ("convergent_motif",):
        # For convergent, we store [source, source, target] — handle specially
        if len(node_ids) >= 2:
            return canonical_key_convergent(node_ids[:-1], node_ids[-1])
        return "::".join(node_ids)
    elif topology_type in ("divergent_motif",):
        # For divergent, we store [source, target, target]
        if len(node_ids) >= 2:
            return canonical_key_divergent(node_ids[0], node_ids[1:])
        return "::".join(node_ids)
    else:
        return canonical_key_pathway(node_ids)


# ---------------------------------------------------------------------------
# Graph Engine
# ---------------------------------------------------------------------------


class MolecularGraphEngine:
    """Generates candidate topologies from Mirror KG molecular connections.

    Design:
      - Builds in-memory adjacency from MirrorRegionConnection rows.
      - Computes SCC (Kosaraju), hubs (top 50 by degree).
      - Generates 9 motif types with per-type caps, real-time canonical dedup.
      - Pre-scores each candidate (0..1), filters below config.pre_score_cutoff.
      - Saves raw candidates to JSONL for downstream phases.
    """

    def __init__(self, config: GraphEngineConfig | None = None):
        self.config = config or GraphEngineConfig()

        # Graph data
        self.nodes: dict[str, NodeInfo] = {}
        self.adjacency: dict[str, set[str]] = {}
        self.reverse_adjacency: dict[str, set[str]] = {}
        self.edges: dict[str, EdgeRecord] = {}

        # Edge index: (source_id, target_id) -> list[edge_id]
        self._edge_by_pair: dict[tuple[str, str], list[str]] = {}

        # Region meta: region_id -> functional_domains
        self._functional_domains: dict[str, list[str]] = {}

        # SCC cache
        self.scc_components: list[set[str]] = []
        self.scc_index: dict[str, int] = {}

        # Hub cache
        self.hubs: list[str] = []
        self.hub_2hop: dict[str, set[str]] = {}

        # Global dedup set
        self._seen: set[str] = set()

        # Candidate accumulator
        self._candidates: list[TopologyCandidate] = []

        # Stats
        self._stats: dict[str, Any] = {
            "motif_counts": {},
            "motif_deduped": {},
            "motif_filtered": {},
            "total_generated": 0,
            "total_after_dedup": 0,
            "total_after_scoring": 0,
            "graph_build_ms": 0,
            "generation_ms": 0,
        }

    # ------------------------------------------------------------------
    # Data Loading
    # ------------------------------------------------------------------

    async def load_from_db(self, session: AsyncSession) -> None:
        """Load molecular connections from Mirror KG."""
        t0 = time.perf_counter()

        # 1. Load candidate brain regions for functional_domains
        region_stmt = select(CandidateBrainRegion).where(
            CandidateBrainRegion.granularity_level == self.config.granularity_level
        )
        region_result = await session.execute(region_stmt)
        region_rows: list[CandidateBrainRegion] = list(region_result.scalars())
        for row in region_rows:
            region_id = str(row.id)
            func_domains = row.raw_payload.get("functional_domains", []) if row.raw_payload else []
            if isinstance(func_domains, str):
                func_domains = [func_domains]
            self._functional_domains[region_id] = func_domains

        # 2. Load connections
        stmt = select(MirrorRegionConnection).where(
            MirrorRegionConnection.granularity_level == self.config.granularity_level
        )

        if self.config.exclude_rejected:
            from app.schemas.mirror_kg import MirrorReviewStatus
            stmt = stmt.where(MirrorRegionConnection.review_status != MirrorReviewStatus.rejected)

        if self.config.min_confidence is not None:
            stmt = stmt.where(
                MirrorRegionConnection.confidence >= self.config.min_confidence
            )

        result = await session.execute(stmt)
        conn_count = 0
        for row in result.scalars():
            conn_id = str(row.id)
            src_id = str(row.source_region_candidate_id) if row.source_region_candidate_id else ""
            tgt_id = str(row.target_region_candidate_id) if row.target_region_candidate_id else ""
            if not src_id or not tgt_id:
                continue

            # Upsert node info from candidate regions
            if src_id not in self.nodes:
                self.nodes[src_id] = NodeInfo(
                    region_id=src_id,
                    functional_domains=self._functional_domains.get(src_id, []),
                )
            if tgt_id not in self.nodes:
                self.nodes[tgt_id] = NodeInfo(
                    region_id=tgt_id,
                    functional_domains=self._functional_domains.get(tgt_id, []),
                )

            # Build adjacency
            if src_id not in self.adjacency:
                self.adjacency[src_id] = set()
            self.adjacency[src_id].add(tgt_id)

            if tgt_id not in self.reverse_adjacency:
                self.reverse_adjacency[tgt_id] = set()
            self.reverse_adjacency[tgt_id].add(src_id)

            # Build edge record
            evidence_count = 0
            raw_payload = row.raw_payload_json or {}
            if isinstance(raw_payload, dict):
                evidence_count = raw_payload.get("evidence_count", 0)
                if isinstance(evidence_count, str):
                    try:
                        evidence_count = int(evidence_count)
                    except (ValueError, TypeError):
                        evidence_count = 0
                elif not isinstance(evidence_count, (int, float)):
                    evidence_count = 0
                evidence_count = int(evidence_count) if evidence_count else 0

            self.edges[conn_id] = EdgeRecord(
                edge_id=conn_id,
                source_id=src_id,
                target_id=tgt_id,
                connection_type=row.connection_type or "",
                directionality=row.directionality or "directed",
                confidence=float(row.confidence) if row.confidence is not None else 0.0,
                evidence_count=evidence_count,
                strength=row.strength,
                modality=row.modality,
            )

            pair_key = (src_id, tgt_id)
            if pair_key not in self._edge_by_pair:
                self._edge_by_pair[pair_key] = []
            self._edge_by_pair[pair_key].append(conn_id)

            conn_count += 1

        elapsed = time.perf_counter() - t0
        self._stats["graph_build_ms"] = round(elapsed * 1000, 1)
        self._stats["node_count"] = len(self.nodes)
        self._stats["edge_count"] = len(self.edges)
        self._stats["connection_rows_loaded"] = conn_count
        logger.info(
            "Graph built: %d nodes, %d edges (from %d conn rows) in %.1fms",
            len(self.nodes), len(self.edges), conn_count, elapsed * 1000,
        )

        # 3. Populate name info from candidate region rows
        node_ids_with_names: set[str] = set()
        for row in region_rows:
            rid = str(row.id)
            if rid in self.nodes:
                self.nodes[rid].name_en = row.en_name or ""
                self.nodes[rid].name_cn = row.cn_name or ""
                node_ids_with_names.add(rid)

    # ------------------------------------------------------------------
    # SCC (Kosaraju)
    # ------------------------------------------------------------------

    def _kosaraju_scc(self) -> tuple[list[set[str]], dict[str, int]]:
        """Compute strongly connected components using Kosaraju's algorithm.

        Uses iterative DFS (avoiding Python recursion depth limits on
        574-node dense graphs) with explicit state stack.
        """
        all_nodes = list(self.nodes.keys())
        visited: set[str] = set()
        order: list[str] = []

        # First pass: DFS post-order (iterative).
        # State stack holds (node, iterator-over-neighbors) pairs.
        for start_node in all_nodes:
            if start_node in visited:
                continue
            call_stack: list[tuple[str, object]] = [(start_node, None)]
            while call_stack:
                v, it = call_stack[-1]
                if v not in visited:
                    visited.add(v)
                    it = iter(self.adjacency.get(v, set()))
                    call_stack[-1] = (v, it)
                # Advance iterator
                try:
                    nb = next(it)  # type: ignore[arg-type]
                    if nb not in visited:
                        call_stack.append((nb, None))
                except StopIteration:
                    call_stack.pop()
                    order.append(v)

        # Second pass: DFS on reversed graph in reverse finishing order.
        visited2: set[str] = set()
        components: list[set[str]] = []
        index: dict[str, int] = {}

        comp_id = 0
        for v in reversed(order):
            if v in visited2:
                continue
            comp: set[str] = set()
            stack = [v]
            while stack:
                cur = stack.pop()
                if cur not in visited2:
                    visited2.add(cur)
                    index[cur] = comp_id
                    comp.add(cur)
                    for nb in self.reverse_adjacency.get(cur, set()):
                        if nb not in visited2:
                            stack.append(nb)
            components.append(comp)
            comp_id += 1

        return components, index

    def compute_scc(self) -> None:
        """Compute and cache SCC components."""
        t0 = time.perf_counter()
        self.scc_components, self.scc_index = self._kosaraju_scc()
        elapsed = time.perf_counter() - t0
        self._stats["scc_count"] = len(self.scc_components)
        self._stats["scc_compute_ms"] = round(elapsed * 1000, 1)
        largest_scc = max((len(c) for c in self.scc_components), default=0)
        self._stats["largest_scc_size"] = largest_scc
        logger.info(
            "SCC: %d components, largest=%d nodes (%.1fms)",
            len(self.scc_components), largest_scc, elapsed * 1000,
        )

    # ------------------------------------------------------------------
    # Hubs
    # ------------------------------------------------------------------

    def compute_hubs(self) -> None:
        """Compute top-K hubs by total degree and their 2-hop neighborhoods."""
        t0 = time.perf_counter()

        degree: dict[str, int] = {}
        all_nodes = list(self.nodes.keys())
        for n in all_nodes:
            out_deg = len(self.adjacency.get(n, set()))
            in_deg = len(self.reverse_adjacency.get(n, set()))
            degree[n] = out_deg + in_deg

        sorted_nodes = sorted(degree.items(), key=lambda x: -x[1])
        self.hubs = [n for n, _ in sorted_nodes[:self.config.hub_count]]

        # Build 2-hop neighborhoods for hubs
        self.hub_2hop = {}
        for hub in self.hubs:
            neighbors: set[str] = set()
            # 1-hop forward
            for nb in self.adjacency.get(hub, set()):
                neighbors.add(nb)
                # 2-hop forward
                for nb2 in self.adjacency.get(nb, set()):
                    neighbors.add(nb2)
            # 1-hop backward
            for nb in self.reverse_adjacency.get(hub, set()):
                neighbors.add(nb)
                # 2-hop backward
                for nb2 in self.reverse_adjacency.get(nb, set()):
                    neighbors.add(nb2)
            neighbors.discard(hub)
            self.hub_2hop[hub] = neighbors

        elapsed = time.perf_counter() - t0
        self._stats["hub_compute_ms"] = round(elapsed * 1000, 1)
        logger.info(
            "Hubs: top-%d nodes by degree (%.1fms)",
            len(self.hubs), elapsed * 1000,
        )

    # ------------------------------------------------------------------
    # Helper: edge selection
    # ------------------------------------------------------------------

    def _get_edge_id(self, src: str, tgt: str) -> str | None:
        """Get the first edge_id for a given (source, target) pair."""
        ids = self._edge_by_pair.get((src, tgt))
        if ids:
            return ids[0]
        return None

    def _get_edge_ids(self, src: str, tgt: str) -> list[str]:
        """Get all edge_ids for a given (source, target) pair."""
        return self._edge_by_pair.get((src, tgt), [])

    def _avg_edge_confidence_for_ids(self, edge_ids: list[str]) -> float:
        """Average confidence across a list of edge IDs."""
        if not edge_ids:
            return 0.0
        total = 0.0
        count = 0
        for eid in edge_ids:
            rec = self.edges.get(eid)
            if rec is not None:
                total += rec.confidence
                count += 1
        return total / count if count > 0 else 0.0

    def _total_evidence_for_ids(self, edge_ids: list[str]) -> int:
        """Sum evidence_count across edge IDs."""
        total = 0
        for eid in edge_ids:
            rec = self.edges.get(eid)
            if rec is not None:
                total += rec.evidence_count
        return total

    def _check_and_dedup(self, canonical_key: str) -> bool:
        """Return True if this key is new (not yet seen)."""
        if canonical_key in self._seen:
            return False
        self._seen.add(canonical_key)
        return True

    # ------------------------------------------------------------------
    # Topology Pre-Scoring
    # ------------------------------------------------------------------

    def _anatomical_consistency(self, candidate: TopologyCandidate) -> float:
        """Score 0..1 for anatomical plausibility.

        Heuristic: prefer paths within same hemisphere / nearby regions.
        For now, use a simple heuristic based on edges having valid connection types.
        """
        if not candidate.edge_ids:
            return 0.0
        valid_types = 0
        for eid in candidate.edge_ids:
            rec = self.edges.get(eid)
            if rec and rec.connection_type and rec.connection_type != "unknown":
                valid_types += 1
        return valid_types / len(candidate.edge_ids)

    def _module_coherence(self, candidate: TopologyCandidate) -> float:
        """Score 0..1 for functional module coherence.

        If all nodes share functional domains, score is higher.
        """
        if not candidate.node_ids:
            return 0.0
        domain_sets: list[set[str]] = []
        for nid in candidate.node_ids:
            node = self.nodes.get(nid)
            if node and node.functional_domains:
                domain_sets.append(set(node.functional_domains))
        if not domain_sets:
            return 0.5  # neutral when no domain info
        # Jaccard-like overlap score
        if len(domain_sets) == 1:
            return 0.7
        intersection = set.intersection(*domain_sets) if len(domain_sets) > 1 else set()
        union = set.union(*domain_sets)
        if not union:
            return 0.5
        return len(intersection) / len(union)

    def _redundancy_penalty(self, candidate: TopologyCandidate) -> float:
        """Penalty 0..1 for redundancy with existing candidates.

        Penalize if this candidate shares many edges with higher-scored ones.
        Simplified: penalize based on degree of hub overlap.
        """
        node_set = set(candidate.node_ids)
        hub_overlap = sum(1 for h in self.hubs if h in node_set)
        if len(candidate.node_ids) == 0:
            return 0.0
        ratio = hub_overlap / len(candidate.node_ids)
        # Moderate penalty: 0 at ratio 0, 1 at ratio 1
        return ratio * 0.5

    def topology_pre_score(self, candidate: TopologyCandidate) -> float:
        """Compute pre-score 0..1 for ranking before LLM judgement."""
        score = 0.0

        # 1. Topology completeness (0-0.25)
        score += 0.25 * (1.0 if candidate.is_closed else 0.7)

        # 2. Average edge confidence (0-0.25)
        avg_conf = self._avg_edge_confidence_for_ids(candidate.edge_ids)
        score += 0.25 * avg_conf

        # 3. Evidence quantity (0-0.20)
        total_ev = candidate.total_evidence
        score += 0.20 * min(1.0, total_ev / 10.0)

        # 4. Anatomical consistency (0-0.15)
        score += 0.15 * self._anatomical_consistency(candidate)

        # 5. Module coherence (0-0.10)
        score += 0.10 * self._module_coherence(candidate)

        # 6. Redundancy penalty (0-0.05)
        score -= 0.05 * self._redundancy_penalty(candidate)

        return max(0.0, min(1.0, score))

    # ------------------------------------------------------------------
    # Candidate creation helper
    # ------------------------------------------------------------------

    def _make_candidate(
        self,
        topology_type: str,
        anatomical_pattern: str,
        is_closed: bool,
        node_ids: list[str],
        edge_ids: list[str],
        extra: dict[str, Any] | None = None,
    ) -> TopologyCandidate | None:
        """Create a TopologyCandidate with pre-score, checking dedup.

        Returns None if already seen or below score cutoff.
        """
        canonical_key = make_canonical_key(node_ids, topology_type)
        if not self._check_and_dedup(canonical_key):
            return None

        avg_conf = self._avg_edge_confidence_for_ids(edge_ids)
        total_ev = self._total_evidence_for_ids(edge_ids)

        candidate = TopologyCandidate(
            topology_type=topology_type,
            anatomical_pattern=anatomical_pattern,
            is_closed=is_closed,
            node_ids=node_ids,
            edge_ids=edge_ids,
            canonical_key=canonical_key,
            avg_confidence=avg_conf,
            total_evidence=total_ev,
            node_count=len(node_ids),
            edge_count=len(edge_ids),
            extra=extra or {},
        )

        candidate.pre_score = self.topology_pre_score(candidate)

        if candidate.pre_score < self.config.pre_score_cutoff:
            return None

        return candidate

    def _accumulate(self, candidate: TopologyCandidate | None) -> bool:
        """Accumulate candidate if not None. Returns True if added."""
        if candidate is None:
            return False
        self._candidates.append(candidate)
        return True

    # ------------------------------------------------------------------
    # Motif Generation
    # ------------------------------------------------------------------

    def generate_directed_cycles_3(self) -> int:
        """Generate A→B→C→A closed 3-node cycles."""
        count = 0
        deduped = 0
        filtered = 0
        motif_type = "directed_cycle_3"
        cap = self.config.max_directed_cycles_3

        for a in self.nodes:
            if count >= cap:
                break
            for b in self.adjacency.get(a, set()):
                if count >= cap:
                    break
                if b == a:
                    continue
                for c in self.adjacency.get(b, set()):
                    if count >= cap:
                        break
                    if c == a or c == b:
                        continue
                    if a in self.adjacency.get(c, set()):
                        edge_ids = []
                        e1 = self._get_edge_id(a, b)
                        e2 = self._get_edge_id(b, c)
                        e3 = self._get_edge_id(c, a)
                        if e1 and e2 and e3:
                            edge_ids = [e1, e2, e3]
                        cand = self._make_candidate(
                            topology_type=motif_type,
                            anatomical_pattern="closed_circuit",
                            is_closed=True,
                            node_ids=[a, b, c],
                            edge_ids=edge_ids,
                        )
                        if cand is None:
                            deduped += 1
                            continue
                        if self._accumulate(cand):
                            count += 1
                        else:
                            filtered += 1

        self._stats["motif_counts"][motif_type] = count
        self._stats["motif_deduped"][motif_type] = deduped
        self._stats["motif_filtered"][motif_type] = filtered
        logger.info("  directed_cycle_3: %d generated, %d deduped", count, deduped)
        return count

    def generate_feedforward_loops_3(self) -> int:
        """Generate A→B, A→C, B→C pattern (no closure requirement)."""
        count = 0
        deduped = 0
        filtered = 0
        motif_type = "feedforward_loop_3"
        cap = self.config.max_feedforward_loops_3

        for a in self.nodes:
            if count >= cap:
                break
            out_a = self.adjacency.get(a, set())
            if len(out_a) < 2:
                continue
            out_list = list(out_a)
            for bi in range(len(out_list)):
                if count >= cap:
                    break
                b = out_list[bi]
                if b == a:
                    continue
                for ci in range(bi + 1, len(out_list)):
                    if count >= cap:
                        break
                    c = out_list[ci]
                    if c == a or c == b:
                        continue
                    if b in self.adjacency.get(c, set()):
                        # Feedforward: A→B, A→C, C→B (B receives from C)
                        edge_ids = []
                        e1 = self._get_edge_id(a, b)
                        e2 = self._get_edge_id(a, c)
                        e3 = self._get_edge_id(c, b)
                        if e1 and e2 and e3:
                            edge_ids = [e1, e2, e3]
                        cand = self._make_candidate(
                            topology_type=motif_type,
                            anatomical_pattern="feedforward_motif",
                            is_closed=False,
                            node_ids=[a, c, b],
                            edge_ids=edge_ids,
                        )
                        if cand is None:
                            deduped += 1
                            continue
                        if self._accumulate(cand):
                            count += 1
                    elif c in self.adjacency.get(b, set()):
                        # Feedforward: A→B, A→C, B→C
                        edge_ids = []
                        e1 = self._get_edge_id(a, b)
                        e2 = self._get_edge_id(a, c)
                        e3 = self._get_edge_id(b, c)
                        if e1 and e2 and e3:
                            edge_ids = [e1, e2, e3]
                        cand = self._make_candidate(
                            topology_type=motif_type,
                            anatomical_pattern="feedforward_motif",
                            is_closed=False,
                            node_ids=[a, b, c],
                            edge_ids=edge_ids,
                        )
                        if cand is None:
                            deduped += 1
                            continue
                        if self._accumulate(cand):
                            count += 1

        self._stats["motif_counts"][motif_type] = count
        self._stats["motif_deduped"][motif_type] = deduped
        self._stats["motif_filtered"][motif_type] = filtered
        logger.info("  feedforward_loop_3: %d generated, %d deduped", count, deduped)
        return count

    def generate_reciprocal_pairs_3(self) -> int:
        """Generate A↔B AND B↔C chains (3-node reciprocal chain).

        Finds nodes where bidirectional edges exist and chains them.
        """
        count = 0
        deduped = 0
        filtered = 0
        motif_type = "reciprocal_pair_3"
        cap = self.config.max_reciprocal_pairs_3

        # Build bidirectional adjacency
        bidirectional: dict[str, set[str]] = {}
        for node in self.nodes:
            out_set = self.adjacency.get(node, set())
            in_set = self.reverse_adjacency.get(node, set())
            mutual = out_set & in_set
            if mutual:
                bidirectional[node] = mutual

        for a in bidirectional:
            if count >= cap:
                break
            for b in bidirectional.get(a, set()):
                if count >= cap:
                    break
                if b <= a:  # avoid A→B / B→A duplicates
                    continue
                for c in bidirectional.get(b, set()):
                    if count >= cap:
                        break
                    if c == a:
                        continue
                    if c in bidirectional.get(a, set()):
                        continue  # A↔C makes a triangle, skip
                    # A↔B and B↔C
                    edge_ids = []
                    e_ab = self._get_edge_id(a, b)
                    e_ba = self._get_edge_id(b, a)
                    e_bc = self._get_edge_id(b, c)
                    e_cb = self._get_edge_id(c, b)
                    if e_ab and e_ba and e_bc and e_cb:
                        edge_ids = [e_ab, e_ba, e_bc, e_cb]
                    cand = self._make_candidate(
                        topology_type=motif_type,
                        anatomical_pattern="feedback_motif",
                        is_closed=False,
                        node_ids=[a, b, c],
                        edge_ids=edge_ids,
                    )
                    if cand is None:
                        deduped += 1
                        continue
                    if self._accumulate(cand):
                        count += 1

        self._stats["motif_counts"][motif_type] = count
        self._stats["motif_deduped"][motif_type] = deduped
        self._stats["motif_filtered"][motif_type] = filtered
        logger.info("  reciprocal_pair_3: %d generated, %d deduped", count, deduped)
        return count

    def generate_convergent_motifs(self) -> int:
        """Generate A→C, B→C convergent motifs.

        Only for top-50 hubs as C (target). Max 20 per hub.
        """
        count = 0
        deduped = 0
        filtered = 0
        motif_type = "convergent_motif"
        cap = self.config.max_convergent_motifs
        max_per = self.config.max_per_hub_convergent

        for hub in self.hubs:
            if count >= cap:
                break
            in_neighbors = list(self.reverse_adjacency.get(hub, set()))
            if len(in_neighbors) < 2:
                continue
            per_hub = 0
            for ai in range(len(in_neighbors)):
                if count >= cap or per_hub >= max_per:
                    break
                a = in_neighbors[ai]
                if a == hub:
                    continue
                for bi in range(ai + 1, len(in_neighbors)):
                    if count >= cap or per_hub >= max_per:
                        break
                    b = in_neighbors[bi]
                    if b == hub or b == a:
                        continue
                    edge_ids = []
                    e1 = self._get_edge_id(a, hub)
                    e2 = self._get_edge_id(b, hub)
                    if e1 and e2:
                        edge_ids = [e1, e2]
                    # Canonical key: sorted sources
                    sorted_sources = sorted([a, b])
                    ck = canonical_key_convergent(sorted_sources, hub)
                    if not self._check_and_dedup(ck):
                        deduped += 1
                        continue
                    avg_conf = self._avg_edge_confidence_for_ids(edge_ids)
                    total_ev = self._total_evidence_for_ids(edge_ids)
                    cand = TopologyCandidate(
                        topology_type=motif_type,
                        anatomical_pattern="convergent_motif",
                        is_closed=False,
                        node_ids=[a, b, hub],
                        edge_ids=edge_ids,
                        canonical_key=ck,
                        avg_confidence=avg_conf,
                        total_evidence=total_ev,
                        node_count=3,
                        edge_count=len(edge_ids),
                    )
                    cand.pre_score = self.topology_pre_score(cand)
                    if cand.pre_score < self.config.pre_score_cutoff:
                        filtered += 1
                        continue
                    if self._accumulate(cand):
                        count += 1
                        per_hub += 1

        self._stats["motif_counts"][motif_type] = count
        self._stats["motif_deduped"][motif_type] = deduped
        self._stats["motif_filtered"][motif_type] = filtered
        logger.info("  convergent_motif: %d generated, %d deduped", count, deduped)
        return count

    def generate_divergent_motifs(self) -> int:
        """Generate A→B, A→C divergent motifs.

        Only for top-50 hubs as A (source). Max 20 per hub.
        """
        count = 0
        deduped = 0
        filtered = 0
        motif_type = "divergent_motif"
        cap = self.config.max_divergent_motifs
        max_per = self.config.max_per_hub_divergent

        for hub in self.hubs:
            if count >= cap:
                break
            out_neighbors = list(self.adjacency.get(hub, set()))
            if len(out_neighbors) < 2:
                continue
            per_hub = 0
            for bi in range(len(out_neighbors)):
                if count >= cap or per_hub >= max_per:
                    break
                b = out_neighbors[bi]
                if b == hub:
                    continue
                for ci in range(bi + 1, len(out_neighbors)):
                    if count >= cap or per_hub >= max_per:
                        break
                    c = out_neighbors[ci]
                    if c == hub or c == b:
                        continue
                    edge_ids = []
                    e1 = self._get_edge_id(hub, b)
                    e2 = self._get_edge_id(hub, c)
                    if e1 and e2:
                        edge_ids = [e1, e2]
                    sorted_targets = sorted([b, c])
                    ck = canonical_key_divergent(hub, sorted_targets)
                    if not self._check_and_dedup(ck):
                        deduped += 1
                        continue
                    avg_conf = self._avg_edge_confidence_for_ids(edge_ids)
                    total_ev = self._total_evidence_for_ids(edge_ids)
                    cand = TopologyCandidate(
                        topology_type=motif_type,
                        anatomical_pattern="divergent_motif",
                        is_closed=False,
                        node_ids=[hub, b, c],
                        edge_ids=edge_ids,
                        canonical_key=ck,
                        avg_confidence=avg_conf,
                        total_evidence=total_ev,
                        node_count=3,
                        edge_count=len(edge_ids),
                    )
                    cand.pre_score = self.topology_pre_score(cand)
                    if cand.pre_score < self.config.pre_score_cutoff:
                        filtered += 1
                        continue
                    if self._accumulate(cand):
                        count += 1
                        per_hub += 1

        self._stats["motif_counts"][motif_type] = count
        self._stats["motif_deduped"][motif_type] = deduped
        self._stats["motif_filtered"][motif_type] = filtered
        logger.info("  divergent_motif: %d generated, %d deduped", count, deduped)
        return count

    def generate_relay_pathways(self) -> int:
        """Generate relay pathways (3-6 nodes) using BFS bounded by depth."""
        count = 0
        deduped = 0
        filtered = 0
        motif_type = "relay_pathway_3_6"
        cap = self.config.max_relay_pathways
        max_depth = self.config.max_relay_depth
        max_paths = self.config.max_paths_per_start

        for start_node in self.nodes:
            if count >= cap:
                break
            # BFS for paths up to max_depth
            paths_found = 0
            # Stack: (current_node, path_nodes, path_edges)
            stack: list[tuple[str, list[str], list[str]]] = [
                (start_node, [start_node], [])
            ]
            while stack and paths_found < max_paths and count < cap:
                cur, path_nodes, path_edges = stack.pop()
                if len(path_nodes) >= 4 and len(path_nodes) <= max_depth + 1:
                    # Yield candidate if >= 3 edges (4 nodes) and <= max_depth+1 nodes
                    cand = self._make_candidate(
                        topology_type=motif_type,
                        anatomical_pattern="open_pathway",
                        is_closed=False,
                        node_ids=list(path_nodes),
                        edge_ids=list(path_edges),
                    )
                    if cand is None:
                        deduped += 1
                    elif self._accumulate(cand):
                        count += 1
                        paths_found += 1
                    else:
                        filtered += 1

                if len(path_nodes) > max_depth:
                    continue

                for nb in self.adjacency.get(cur, set()):
                    if nb in path_nodes:
                        continue  # avoid cycles in relay pathways
                    eid = self._get_edge_id(cur, nb)
                    new_edges = list(path_edges)
                    if eid:
                        new_edges = path_edges + [eid]
                    stack.append((nb, path_nodes + [nb], new_edges))

        self._stats["motif_counts"][motif_type] = count
        self._stats["motif_deduped"][motif_type] = deduped
        self._stats["motif_filtered"][motif_type] = filtered
        logger.info("  relay_pathway_3_6: %d generated, %d deduped", count, deduped)
        return count

    def _bounded_dfs_cycles(
        self,
        start: str,
        max_depth: int,
        cap_remaining: int,
        motif_type: str,
    ) -> list[TopologyCandidate]:
        """Bounded DFS to find cycles of length 4..max_depth from start node."""
        results: list[TopologyCandidate] = []
        stack: list[tuple[str, list[str], list[str]]] = [
            (start, [start], [])
        ]
        visited_depth: dict[str, int] = {}

        while stack and len(results) < cap_remaining:
            cur, path_nodes, path_edges = stack.pop()

            if len(path_nodes) > max_depth:
                continue

            # Check if current node has a connection back to start (closing the loop)
            if len(path_nodes) >= 4 and start in self.adjacency.get(cur, set()):
                # Found a cycle: path_nodes + start
                cycle_nodes = path_nodes[:]
                cycle_edges = list(path_edges)
                closing_eid = self._get_edge_id(cur, start)
                if closing_eid:
                    cycle_edges.append(closing_eid)
                cand = self._make_candidate(
                    topology_type=motif_type,
                    anatomical_pattern="closed_circuit",
                    is_closed=True,
                    node_ids=cycle_nodes,
                    edge_ids=cycle_edges,
                )
                if cand is not None:
                    results.append(cand)
                    if len(results) >= cap_remaining:
                        break

            # Prune: avoid revisiting nodes already in path (except start for closing)
            for nb in self.adjacency.get(cur, set()):
                if nb in path_nodes:
                    if nb == start and len(path_nodes) >= 3:
                        # This will be caught when checking start above; skip here
                        pass
                    continue
                # Prune: don't revisit at same depth
                depth_key = f"{nb}_{len(path_nodes)}"
                if depth_key in visited_depth:
                    continue
                visited_depth[depth_key] = len(path_nodes)
                eid = self._get_edge_id(cur, nb)
                new_edges = list(path_edges)
                if eid:
                    new_edges = path_edges + [eid]
                stack.append((nb, path_nodes + [nb], new_edges))

        return results

    def generate_closed_loops_4_8(self) -> int:
        """Generate 4-8 node closed loops within SCCs.

        For SCCs <= 50 nodes, exhaustive bounded DFS.
        For larger SCCs, limit to config.max_loops_bounded_dfs per SCC.
        """
        count = 0
        motif_type = "closed_loop_4_8"
        cap = self.config.max_closed_loops_4_8

        for comp in self.scc_components:
            if count >= cap:
                break
            comp_size = len(comp)
            if comp_size < 3:
                continue

            per_scc_limit = cap - count
            if comp_size > self.config.scc_small_threshold:
                per_scc_limit = min(
                    per_scc_limit,
                    self.config.max_loops_bounded_dfs,
                )

            scc_nodes = list(comp)
            # Only search from a sample of start nodes in large SCCs
            if comp_size > self.config.scc_small_threshold:
                # Sort by degree descending and take top 20% as start seeds
                degree_map = {
                    n: len(self.adjacency.get(n, set()))
                    for n in scc_nodes
                }
                sorted_scc = sorted(degree_map, key=degree_map.get, reverse=True)
                sample_size = max(10, comp_size // 5)
                start_nodes = sorted_scc[:sample_size]
            else:
                start_nodes = scc_nodes

            for start in start_nodes:
                if count >= cap:
                    break
                remaining = min(cap - count, per_scc_limit)
                if remaining <= 0:
                    break
                results = self._bounded_dfs_cycles(
                    start=start,
                    max_depth=8,
                    cap_remaining=remaining,
                    motif_type=motif_type,
                )
                for cand in results:
                    if self._accumulate(cand):
                        count += 1
                        if count >= cap:
                            break

        self._stats["motif_counts"][motif_type] = count
        logger.info("  closed_loop_4_8: %d generated", count)
        return count

    def generate_cortico_subcortical_loops(self) -> int:
        """Generate loops that include at least one cortical and one subcortical region.

        Uses SCC + hub neighborhoods. Relies on functional_domains for classification.
        """
        count = 0
        deduped = 0
        motif_type = "cortico_subcortical_loop"
        cap = self.config.max_cortico_subcortical_loops

        # Heuristic: treat regions with certain functional domains as cortical
        # and others as subcortical. In molecular_attr data, this is a best-effort.
        cortical_keywords = {"cortex", "visual", "auditory", "somatosensory",
                             "motor", "prefrontal", "temporal", "parietal",
                             "occipital", "frontal", "cingulate", "insular"}
        subcortical_keywords = {"thalamus", "basal ganglia", "cerebellum",
                                "brainstem", "hippocampus", "amygdala",
                                "hypothalamus", "striatum", "globus pallidus",
                                "substantia nigra", "subthalamic"}

        cortical: set[str] = set()
        subcortical: set[str] = set()

        for nid, node in self.nodes.items():
            for dom in node.functional_domains:
                dl = dom.lower()
                if any(kw in dl for kw in cortical_keywords):
                    cortical.add(nid)
                if any(kw in dl for kw in subcortical_keywords):
                    subcortical.add(nid)
            # Fallback: from name_en
            name_en = (node.name_en or "").lower()
            if any(kw in name_en for kw in cortical_keywords):
                cortical.add(nid)
            if any(kw in name_en for kw in subcortical_keywords):
                subcortical.add(nid)

        # For each hub, explore SCC-limited cycles that span both categories
        for hub in self.hubs:
            if count >= cap:
                break
            if hub not in self.scc_index:
                continue
            comp_id = self.scc_index[hub]
            comp = self.scc_components[comp_id]

            has_cortical = any(n in cortical for n in comp)
            has_subcortical = any(n in subcortical for n in comp)
            if not (has_cortical and has_subcortical):
                continue

            # Bounded DFS from hub looking for cycles that include both types
            remaining = cap - count
            results = self._bounded_dfs_cycles(
                start=hub,
                max_depth=8,
                cap_remaining=remaining,
                motif_type=motif_type,
            )
            for cand in results:
                node_ids_set = set(cand.node_ids)
                found_cortical = any(n in cortical for n in node_ids_set)
                found_subcortical = any(n in subcortical for n in node_ids_set)
                if found_cortical and found_subcortical:
                    if self._accumulate(cand):
                        count += 1
                else:
                    deduped += 1
                if count >= cap:
                    break

        self._stats["motif_counts"][motif_type] = count
        self._stats["motif_deduped"][motif_type] = deduped
        logger.info("  cortico_subcortical_loop: %d generated, %d skipped", count, deduped)
        return count

    def generate_cross_module_loops(self) -> int:
        """Generate cycles spanning >= 2 functional modules.

        After module classification, finds loops in SCCs where nodes belong
        to different functional modules.
        """
        count = 0
        motif_type = "cross_module_loop"
        cap = self.config.max_cross_module_loops

        # Group nodes by functional domain modules
        module_regions: dict[str, set[str]] = {}
        for nid, node in self.nodes.items():
            for dom in node.functional_domains:
                if dom not in module_regions:
                    module_regions[dom] = set()
                module_regions[dom].add(nid)

        # For each SCC, check if it spans multiple modules
        for comp in self.scc_components:
            if count >= cap:
                break
            # Find which modules are represented in this SCC
            comp_modules: dict[str, list[str]] = {}
            for nid in comp:
                node = self.nodes.get(nid)
                if node:
                    for dom in node.functional_domains:
                        if dom not in comp_modules:
                            comp_modules[dom] = []
                        comp_modules[dom].append(nid)
            if len(comp_modules) < 2:
                continue

            # Search for cycles from nodes in different modules
            comp_list = list(comp)
            for nid in comp_list:
                if count >= cap:
                    break
                remaining = cap - count
                results = self._bounded_dfs_cycles(
                    start=nid,
                    max_depth=8,
                    cap_remaining=remaining,
                    motif_type=motif_type,
                )
                for cand in results:
                    node_domains: set[str] = set()
                    for cn in cand.node_ids:
                        node_obj = self.nodes.get(cn)
                        if node_obj:
                            node_domains.update(node_obj.functional_domains)
                    if len(node_domains) >= 2:
                        if self._accumulate(cand):
                            count += 1
                    if count >= cap:
                        break

        self._stats["motif_counts"][motif_type] = count
        logger.info("  cross_module_loop: %d generated", count)
        return count

    # ------------------------------------------------------------------
    # Generation Orchestration
    # ------------------------------------------------------------------

    def generate_all_motifs(self) -> int:
        """Run all motif generators in order. Returns total generated."""
        t0 = time.perf_counter()
        total = 0

        generators = [
            ("directed_cycle_3", self.generate_directed_cycles_3),
            ("feedforward_loop_3", self.generate_feedforward_loops_3),
            ("reciprocal_pair_3", self.generate_reciprocal_pairs_3),
            ("convergent_motif", self.generate_convergent_motifs),
            ("divergent_motif", self.generate_divergent_motifs),
            ("relay_pathway_3_6", self.generate_relay_pathways),
            ("closed_loop_4_8", self.generate_closed_loops_4_8),
            ("cortico_subcortical_loop", self.generate_cortico_subcortical_loops),
            ("cross_module_loop", self.generate_cross_module_loops),
        ]

        for name, gen in generators:
            subtotal = gen()
            total += subtotal
            logger.info("  %s: %d total after generation", name, subtotal)

        elapsed = time.perf_counter() - t0
        self._stats["generation_ms"] = round(elapsed * 1000, 1)
        self._stats["total_generated"] = len(self._candidates)
        self._stats["total_after_dedup"] = len(self._candidates)
        logger.info(
            "All motifs generated: %d candidates in %.1fms",
            len(self._candidates), elapsed * 1000,
        )

        return total

    # ------------------------------------------------------------------
    # JSONL Output
    # ------------------------------------------------------------------

    def save_to_jsonl(self, output_dir: str | Path) -> Path:
        """Save raw topology candidates to JSONL file.

        Returns the path to the saved file.
        """
        output_path = Path(output_dir) / "raw_topology_candidates.jsonl"
        output_path.parent.mkdir(parents=True, exist_ok=True)

        # Sort by pre_score descending
        sorted_candidates = sorted(
            self._candidates,
            key=lambda c: c.pre_score,
            reverse=True,
        )

        with output_path.open("w", encoding="utf-8") as f:
            for cand in sorted_candidates:
                f.write(json.dumps(cand.to_dict(), ensure_ascii=False, default=str) + "\n")

        self._stats["total_after_scoring"] = len(sorted_candidates)
        logger.info(
            "Saved %d candidates to %s",
            len(sorted_candidates), output_path,
        )
        return output_path

    # ------------------------------------------------------------------
    # Public Interface
    # ------------------------------------------------------------------

    async def build_graph_and_generate_candidates(
        self,
        session: AsyncSession,
    ) -> GraphEngineResult:
        """Main entry point: load data, build graph, compute SCC/hubs,
        generate all motifs, pre-score, and return results.

        Args:
            session: AsyncSession for DB queries.

        Returns:
            GraphEngineResult with nodes, edges, adjacency, candidates, stats.
        """
        # Phase 1: Load data
        await self.load_from_db(session)

        # Phase 2: Compute SCC and hubs
        self.compute_scc()
        self.compute_hubs()

        # Phase 3: Generate all motifs
        self.generate_all_motifs()

        # Sort candidates by pre_score descending
        self._candidates.sort(key=lambda c: c.pre_score, reverse=True)

        # Build stats summary
        motif_counts = self._stats.get("motif_counts", {})
        self._stats["summary"] = {
            "nodes": len(self.nodes),
            "edges": len(self.edges),
            "scc_components": len(self.scc_components),
            "hubs": len(self.hubs),
            "total_candidates": len(self._candidates),
            "motif_breakdown": dict(motif_counts),
        }

        return GraphEngineResult(
            nodes=self.nodes,
            edges=self.edges,
            adjacency=self.adjacency,
            candidates=self._candidates,
            stats=dict(self._stats),
        )


# ---------------------------------------------------------------------------
# Convenience function
# ---------------------------------------------------------------------------


async def build_graph_and_generate_candidates(
    session: AsyncSession,
    config: GraphEngineConfig | None = None,
    output_dir: str | Path | None = None,
) -> GraphEngineResult:
    """Convenience wrapper to build graph, generate candidates, save JSONL.

    Args:
        session: AsyncSession for DB queries.
        config: Optional engine config overrides.
        output_dir: Directory for JSONL output. If None, uses temp dir.

    Returns:
        GraphEngineResult with all data and stats.
    """
    engine = MolecularGraphEngine(config or GraphEngineConfig())
    result = await engine.build_graph_and_generate_candidates(session)

    if output_dir is not None:
        jsonl_path = engine.save_to_jsonl(output_dir)
        result.stats["jsonl_path"] = str(jsonl_path)
    else:
        # Save to temp dir
        tmp_dir = tempfile.mkdtemp(prefix="mol_circuit_")
        jsonl_path = engine.save_to_jsonl(tmp_dir)
        result.stats["jsonl_path"] = str(jsonl_path)

    return result
